image: python

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python --version
  - pip install pipenv
  - pipenv --version
  - pipenv install

all:
  script:
    - pipenv run make style_check
    - pipenv run make build
    - pipenv run make tests_all
